### ISSUE TITLE
Unable to find an element with the role "option" when used with datalist element

### ISSUE THREAD

**Issue by SirRegion** [testing-library/react-testing-library#1003]
- `@testing-library/dom` version: 8.11.1
- Testing Framework and version: jest 26.0.24
- DOM Environment: jest-dom 5.14.1

### Relevant code or config:

The Test:
```js
import React from "react";
import { render, screen} from "@testing-library/react";
import minExample from "./min-example";

test("min example", () => {
    render(<minExample/>)
    const options = screen.getAllByRole('option', {hidden: true});
})
```

The Component:
```js

import React from 'react';

export default class minExample extends React.Component<any, any>{

    render() {
        return <datalist>
            <option name={"test"}>Testing!</option>
            <option>More Options!</option>
        </datalist>;
    }
}
```

### What you did:

When trying to find the options of a datalist, the testing library fails to find any.  (I am using react-testing-library, but because the bug seems to be inside the this library, I'm opening the issue here.)

### What happened:

The following error appeared:

```
Unable to find an element with the role "option"

There are no available roles.

    Ignored nodes: comments, <script />, <style />
<body>
<div>
    <minexample />
</div>
</body>
TestingLibraryElementError: Unable to find an element with the role "option"

There are no available roles.

    Ignored nodes: comments, <script />, <style />
<body>
<div>
    <minexample />
</div>
</body>
at Object.getElementError (C:\Users\username\PhpstormProjects\projectname\node_modules\@testing-library\dom\dist\config.js:38:19)
at C:\Users\username\PhpstormProjects\projectname\node_modules\@testing-library\dom\dist\query-helpers.js:90:38
at getAllByRole (C:\Users\username\PhpstormProjects\projectname\node_modules\@testing-library\dom\dist\query-helpers.js:130:15)
at Object.<anonymous> (C:\Users\username\PhpstormProjects\projectname\src\app\min-example\min-example.test.tsx:8:28)
at Promise.then.completed (C:\Users\username\PhpstormProjects\projectname\node_modules\jest-circus\build\utils.js:276:28)
at new Promise (<anonymous>)
    at callAsyncCircusFn (C:\Users\username\PhpstormProjects\projectname\node_modules\jest-circus\build\utils.js:216:10)
    at _callCircusTest (C:\Users\username\PhpstormProjects\projectname\node_modules\jest-circus\build\run.js:212:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at _runTest (C:\Users\username\PhpstormProjects\projectname\node_modules\jest-circus\build\run.js:149:3)
    at _runTestsForDescribeBlock (C:\Users\username\PhpstormProjects\projectname\node_modules\jest-circus\build\run.js:63:9)
    at run (C:\Users\username\PhpstormProjects\projectname\node_modules\jest-circus\build\run.js:25:3)
    at runAndTransformResultsToJestFormat (C:\Users\username\PhpstormProjects\projectname\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapterInit.js:176:21)
    at jestAdapter (C:\Users\username\PhpstormProjects\projectname\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapter.js:109:19)
    at runTestInternal (C:\Users\username\PhpstormProjects\projectname\node_modules\jest-runner\build\runTest.js:380:16)
    at runTest (C:\Users\username\PhpstormProjects\projectname\node_modules\jest-runner\build\runTest.js:472:34)

```

### Reproduction:

The above code is already a minimum reproducible example.

### Problem description:

Not finding the options of a datalist makes it really hard to test anything that relies on datalists.

**Comment by SirRegion** [comment]
Thank you, this fixes my example. :)

I'll update the example and close this issue, hopefully it will help someone else if they run into same issue.
