### ISSUE TITLE
Using react-router-dom not working as documented

### ISSUE THREAD

**Issue by JanHuege** [testing-library/react-testing-library#1012]
- `@testing-library/react` version: 12.0.0
- Testing Framework and version: jest: 26.6.3
- DOM Environment: jsdom: 16.4.0

### Relevant code or config:

```ts
import React from 'react';
import { Link, Route, Router, Switch, useLocation } from 'react-router-dom';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { createMemoryHistory } from 'history';

const About = () => <div>You are on the about page</div>;
const Home = () => <div>You are home</div>;
const NoMatch = () => <div>No match</div>;

const LocationDisplay = () => {
    const location = useLocation();

    return <div data-testid="location-display">{location.pathname}</div>;
};

const App = () => (
    <div>
        <Link to="/">Home</Link>

        <Link to="/about">About</Link>

        <Switch>
            <Route exact={true} path="/">
                <Home />
            </Route>

            <Route path="/about">
                <About />
            </Route>

            <Route>
                <NoMatch />
            </Route>
        </Switch>

        <LocationDisplay />
    </div>
);

describe('router in ui tests', () => {
    it('should ...', async () => {
        const history = createMemoryHistory();
        render(
            <Router history={history}>
                <App />
            </Router>
        );

        expect(screen.getByText(/you are home/i)).toBeInTheDocument();

        userEvent.click(screen.getByText(/about/i), { button: 0 });

        expect(screen.getByText(/about page/i)).toBeInTheDocument();
    });
});


```

### What you did:

Trying out code from docs: https://testing-library.com/docs/example-react-router/

### What happened:

Test is red.

### Reproduction:

run the code

### Problem description:

Not routing to /about.

```
TestingLibraryElementError: Unable to find an element with the text: /about page/i. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

Ignored nodes: comments, <script />, <style />
<body>
  <div>
    <div>
      <a
        href="/"
      >
        Home
      </a>
      <a
        href="/about"
      >
        About
      </a>
      <div>
        No match
      </div>
      <div
        data-testid="location-display"
      />
    </div>
  </div>
</body>

    at Object.getElementError (C:\projekte\BMW\integrate-full\.yarn\cache\@testing-library-dom-npm-8.2.0-79d1575591-33a0a28ba3.zip\node_modules\@testing-library\dom\dist\config.js:37:19)
    at C:\projekte\BMW\integrate-full\.yarn\cache\@testing-library-dom-npm-8.2.0-79d1575591-33a0a28ba3.zip\node_modules\@testing-library\dom\dist\query-helpers.js:90:38
    at C:\projekte\BMW\integrate-full\.yarn\cache\@testing-library-dom-npm-8.2.0-79d1575591-33a0a28ba3.zip\node_modules\@testing-library\dom\dist\query-helpers.js:62:17
    at C:\projekte\BMW\integrate-full\.yarn\cache\@testing-library-dom-npm-8.2.0-79d1575591-33a0a28ba3.zip\node_modules\@testing-library\dom\dist\query-helpers.js:111:19
    at Object.<anonymous> (C:\projekte\BMW\integrate-full\lib\@integrate\testing\render\__spec__\render.router.spec.ui.tsx:56:23)
    at Object.asyncJestTest (C:\projekte\BMW\integrate-full\.yarn\cache\jest-jasmine2-npm-26.6.3-aba0c11c28-18b15901f8.zip\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:106:37)
    at C:\projekte\BMW\integrate-full\.yarn\cache\jest-jasmine2-npm-26.6.3-aba0c11c28-18b15901f8.zip\node_modules\jest-jasmine2\build\queueRunner.js:45:12
    at new Promise (<anonymous>)
    at mapper (C:\projekte\BMW\integrate-full\.yarn\cache\jest-jasmine2-npm-26.6.3-aba0c11c28-18b15901f8.zip\node_modules\jest-jasmine2\build\queueRunner.js:28:19)
    at C:\projekte\BMW\integrate-full\.yarn\cache\jest-jasmine2-npm-26.6.3-aba0c11c28-18b15901f8.zip\node_modules\jest-jasmine2\build\queueRunner.js:75:41
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

```

**Comment by JanHuege** [comment]
Looks like there is an issue in the project I am working on causing this behavior. But still documentation is not updated with react-router-dom v6+
