### ISSUE TITLE
waitForElementToBeRemoved doesn't work as expect.

### ISSUE THREAD

**Issue by mrdulin** [testing-library/react-testing-library#1033]
- `@testing-library/react` version: `^11.2.7`
- Testing Framework and version:  "jest": "^26.6.3"

### Relevant code or config:

```jsx
import React, { useState } from 'react';

export const MyComp = () => {
  const [listVisible, setListVisible] = useState(true);
  console.log(listVisible);
  return (
    <>
      {listVisible && (
        <ul data-testid="list">
          <li>item 1</li>
        </ul>
      )}
      <button onClick={() => setListVisible(false)}>query</button>
    </>
  );
};
```

### What you did:

First try:

```jsx
import { render, screen, waitForElementToBeRemoved } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import '@testing-library/jest-dom/extend-expect';
import React from 'react';
import { MyComp } from './';

describe('MyComp', () => {
  test('should pass', async () => {
    render(<MyComp />);
    const listContainer = screen.getByTestId('list');
    expect(listContainer).toBeInTheDocument();
    const queryButton = screen.getByRole('button');

    await waitForElementToBeRemoved(() => screen.queryByTestId('list'));
    userEvent.click(queryButton);
  });
});
```

Test result:
```bash
  console.log
    true

      at MyComp (stackoverflow/71706044/index.tsx:5:11)

 FAIL  stackoverflow/71706044/index.test.tsx (11.354 s)
  MyComp
    ✕ should pass (1099 ms)

  ● MyComp › should pass

    Timed out in waitForElementToBeRemoved.

    <html>
      <head />
      <body>
        <div>
          <ul
            data-testid="list"
          >
            <li>
              item 1
            </li>
          </ul>
          <button>
            query
          </button>
        </div>
      </body>
    </html>

      12 |     const queryButton = screen.getByRole('button');
      13 | 
    > 14 |     await waitForElementToBeRemoved(() => screen.queryByTestId('list'));
         |           ^
      15 |     userEvent.click(queryButton);
      16 |   });
      17 | });

      at Object.waitForElementToBeRemoved (node_modules/@testing-library/dom/dist/wait-for-element-to-be-removed.js:22:24)
```

Second try:
```jsx
import { render, screen, waitForElementToBeRemoved } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import '@testing-library/jest-dom/extend-expect';
import React from 'react';
import { MyComp } from './';

describe('MyComp', () => {
  test('should pass', async () => {
    render(<MyComp />);
    const listContainer = screen.getByTestId('list');
    expect(listContainer).toBeInTheDocument();
    const queryButton = screen.getByRole('button');

    userEvent.click(queryButton);
    await waitForElementToBeRemoved(() => screen.queryByTestId('list'));
  });
});
```

Test result:
```bash
 FAIL  stackoverflow/71706044/index.test.tsx (9.495 s)
  MyComp
    ✕ should pass (112 ms)

  ● MyComp › should pass

    The element(s) given to waitForElementToBeRemoved are already removed. waitForElementToBeRemoved requires that the element(s) exist(s) before waiting for removal.

      13 | 
      14 |     userEvent.click(queryButton);
    > 15 |     await waitForElementToBeRemoved(() => screen.queryByTestId('list'));
         |           ^
      16 |   });
      17 | });
      18 | 

      at initialCheck (node_modules/@testing-library/dom/dist/wait-for-element-to-be-removed.js:16:11)
      at stackoverflow/71706044/index.test.tsx:15:11
      at stackoverflow/71706044/index.test.tsx:8:71
      at Object.<anonymous>.__awaiter (stackoverflow/71706044/index.test.tsx:4:12)
      at Object.<anonymous> (stackoverflow/71706044/index.test.tsx:8:34)

  console.log
    true

      at MyComp (stackoverflow/71706044/index.tsx:5:11)

  console.log
    false

      at MyComp (stackoverflow/71706044/index.tsx:5:11)
```

### Problem description:

`waitForElementToBeRemoved` doesn't work as expect. Please explain what's the reason.

**Comment by MatanBobi** [comment]
Hi @mrdulin, thanks for taking the time to open this one.
The approach should definitely be the second one, but, `waitForElementToBeRemoved` is meant to await for async operations and in the example attached, you don't have anything async but just a simple react state change.
In that scenario, there's no need to wait for anything. Once you're using `user-event`, we wrap your operation with `act` and make sure that all the effects have finished (flushing the state changes for example) so you're guaranteed that after the `click` row, the state has already changed.

I'm closing this one as this isn't an issue with the library. If you believe that after my explanation it still is, please write it here. Thanks again.
