### ISSUE TITLE
`act` warning when rendering ReactDataGrid

### ISSUE THREAD

**Issue by sophyphreak** [testing-library/react-testing-library#1086]
- `@testing-library/react` version: 13.3.0
- Testing Framework and version: `jest` 27.4.3
  
- DOM Environment: jsdom, not sure which version
  

### Relevant code or config:

```js
// App.test.js

import App from "./App";
import { render } from "@testing-library/react";

test(`should render App`, () => {
  render(<App />);
});
```

```js
// App.js

import React, { useState, useCallback } from "react";

import ReactDataGrid from "@inovua/reactdatagrid-community";
import "@inovua/reactdatagrid-community/index.css";

import BoolEditor from "@inovua/reactdatagrid-community/BoolEditor";
import SelectEditor from "@inovua/reactdatagrid-community/SelectEditor";

const gridStyle = { minHeight: 320 };

const peopleData = [
  { id: 1, name: "Will", country: "de", citizen: true },
  { id: 2, name: "Bill", country: "fr", citizen: true },
  { id: 3, name: "Matt", country: "rus", citizen: true },
  { id: 4, name: "Steve", country: "jpn", citizen: true },
  { id: 5, name: "John", country: "cn", citizen: true },
  { id: 6, name: "Tom", country: "it", citizen: true },
  { id: 7, name: "Tim", country: "mx", citizen: true }
];

const countryData = [
  { id: "uk", label: "United Kindom" },
  { id: "usa", label: "United States" },
  { id: "can", label: "Canada" },
  { id: "aus", label: "Australia" },
  { id: "jpn", label: "Japan" },
  { id: "cn", label: "China" },
  { id: "fr", label: "France" },
  { id: "de", label: "Germany" },
  { id: "it", label: "Italy" },
  { id: "mx", label: "Mexico" },
  { id: "bz", label: "Brazil" },
  { id: "rus", label: "Russia" },
  { id: "in", label: "India" }
];

const columns = [
  {
    name: "id",
    header: "Id",
    defaultVisible: false,
    minWidth: 100,
    type: "number"
  },
  {
    name: "name",
    header: "Name",
    defaultFlex: 1,
    minWidth: 200,
    maxWidth: 300
  },
  {
    name: "country",
    header: "Country",
    defaultFlex: 1,
    width: 100,
    render: ({ value }) => {
      const tObj = countryData.find((country) => country.id === value);
      return tObj ? tObj.label : "?Unknown?";
    },
    editor: SelectEditor,
    editorProps: {
      idProperty: "id",
      dataSource: countryData,
      collapseOnSelect: true,
      clearIcon: null
    }
  },
  {
    name: "citizen",
    header: "Citizen?",
    width: 100,
    render: ({ value }) => (value ? "yes" : "no"),
    editor: BoolEditor
  }
];

const App = () => {
  const [dataSource, setDataSource] = useState(peopleData);

  const onEditComplete = useCallback(
    ({ value, columnId, rowIndex }) => {
      const data = [...dataSource];
      data[rowIndex] = Object.assign({}, data[rowIndex], { [columnId]: value });

      setDataSource(data);
    },
    [dataSource]
  );

  return (
    <div>
      <h3>Persons Manager </h3>
      <ReactDataGrid
        idProperty="id"
        style={gridStyle}
        editable={true}
        onEditComplete={onEditComplete}
        columns={columns}
        dataSource={dataSource}
      />
    </div>
  );
};

export default () => <App />;
```

### What you did:

ran `npm t`

### What happened:

```bash
  console.error
    Warning: An update to null inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at /Users/andrewhorn/workspace/reactdatagrid-example/node_modules/@inovua/reactdatagrid-community/factory.js:218:41
        at TheGrid (/Users/andrewhorn/workspace/reactdatagrid-example/node_modules/@inovua/reactdatagrid-community/factory.js:1659:43)
        at div
        at App (/Users/andrewhorn/workspace/reactdatagrid-example/src/App.js:79:39)
        at _default

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at warnIfUpdatesNotWrappedWithActDEV (node_modules/react-dom/cjs/react-dom.development.js:27589:9)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:25508:5)
      at dispatchSetState (node_modules/react-dom/cjs/react-dom.development.js:17527:7)
      at node_modules/@inovua/reactdatagrid-community/hooks/useDataSource/computeData.js:218:21
      at node_modules/@inovua/reactdatagrid-community/utils/batchUpdate.js:37:18
```

^Printed 7 times in a row

### Reproduction:

https://github.com/sophyphreak/reactdatagrid-example

Was not able to reproduce in Codesandbox

### Problem description:

All changes happen within imported component from NPM module. I don't think this should trigger `act` warnings since all I'm doing is rendering the component.

### Suggested solution:

I'm not sure these warnings should fire when they're happening in a `render()`.

**Comment by sophyphreak** [comment]
This is what I ended up doing:
```js
import App from "./App";
import { render } from "@testing-library/react";
import { act } from "react-dom/test-utils";

test(`should render App`, async () => {
  const promise = Promise.resolve();
  render(<App />);
  await act(async () => {
    await promise;
  });
});
```
I think it's good enough for me.
