### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'current') on `render` call

### ISSUE THREAD

**Issue by benjamindean** [testing-library/react-testing-library#1200]
### Vesrions

- `@testing-library/react` version: 12.1.5
- Testing Framework and version: `jest`@27
- DOM Environment: `jest-environment-jsdom`@27
- Node 16.5.0
### Relevant code or config:

Even the most basic test fails.

```js
import React from 'react';
import { render, screen } from '@testing-library/react';

...

const { baseElement } = render(
   <Component />,
);

```

### What you did:

Tried many older versions of the testing library and jsdom, but got the same result. Probably important to mention that the codebase in TypeScript.

### What happened:

```bash
TypeError: Cannot read properties of undefined (reading 'current')

      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:909:55)
      at cleanupAtContainer (node_modules/@testing-library/react/dist/pure.js:143:26)
          at Set.forEach (<anonymous>)
      at cleanup (node_modules/@testing-library/react/dist/pure.js:137:21)
      at Object.<anonymous> (node_modules/@testing-library/react/dist/index.js:33:25)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:173:3)
```

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), or a link to a repository on GitHub.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by benjamindean** [comment]
@eps1lon My apologies for the false alarm. Found the culprit. It was an automock of `react-dom` in the `__mocks__` folder. The mock looked like that:

```js
const ReactDOM = jest.genMockFromModule('react-dom');

function mockCreatePortal(element, target) {
    return (element);
}

ReactDOM.createPortal = mockCreatePortal;
```

It messed up the original `react-dom`. After removing the mock everything works correctly.
