### ISSUE TITLE
I am using Signalr in react and writing unit test, but test cases fails where signalr used

### ISSUE THREAD

**Issue by muhammadali-HazelSoft** [testing-library/react-testing-library#1245]
TypeError: Cannot read properties of undefined (reading 'availableTransports')

      at Object.availableTransports [as success] (node_modules/signalr/jquery.signalR.js:733:33)
      at apply (node_modules/jquery/dist/jquery.js:3223:31)
      at Object.fire [as resolveWith] (node_modules/jquery/dist/jquery.js:3353:7)
      at resolveWith (node_modules/jquery/dist/jquery.js:9627:14)
      at XMLHttpRequest.complete (node_modules/jquery/dist/jquery.js:9880:10)
      at XMLHttpRequest.invokeTheCallbackFunction (node_modules/jsdom/lib/jsdom/living/generated/EventHandlerNonNull.js:14:28)
      at XMLHttpRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:35:32)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:350:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
      at XMLHttpRequestImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
      at fireAnEvent (node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
      at requestErrorSteps (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:131:3)
      at Object.dispatchError (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:60:3)
      at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
      at NodeClientRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:121:14)
      at NodeClientRequest.Object.<anonymous>.NodeClientRequest.emit (node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:299:22)

**Comment by MatanBobi** [comment]
This issue is not related to testing-library as we're not providing the environment you're running in.
Based on the error, this looks like an issue in JSDOM (your test environment). Having said that, I don't think using signalr as part of your tests is a good idea because you'll also need to mock the server for those use cases and that can be hard and tricky.

**Comment by MatanBobi** [comment]
That even adds more to the fact that it's because of your testing environment and not because of testing-library.
SignalR requires some browser capabilities that might not be available in your testing environment. If you believe it's an issue, I suggest opening an issue in JSDOM but I highly believe that this can be asked in stackoverflow.

**Comment by muhammadali-HazelSoft** [comment]
@MatanBobi  Thank you for your help.
