### ISSUE TITLE
Error when rendering a shadow dom component

### ISSUE THREAD

**Issue by ReasonableDeveloper** [testing-library/react-testing-library#412]
Hey, first of all I would like to thank you all for this amazing testing library. I've only been using it for a couple of days and I already love it! 😍

### Versions
- `@testing-library/react` version: 8.0.5
- `react` version: 16.8.6
- `node` version: 12.5
- `yarn` version: 1.16

### Relevant code or config:

```jsx
const SampleComponent = () => (
  <div data-testid="root">
    <shadowRoot.div>
      <div>Test</div>
    </shadowRoot.div>
  </div>
)
```

### What you did:

Try to render a shadow dom implementation. I was using  https://github.com/Wildhoney/ReactShadow

### What happened:

In Codesandbox I'm getting timeouts. In my actual code, the tests are failing with following message

`TypeError: l.attachShadow is not a function`

### Reproduction:

https://codesandbox.io/s/react-testing-library-examples-ps3ld

### Problem description:

I assume this is a bug in this library since my app runs fine and upon inspecting via devtools, I can see the shadow DOM (in the DOM :grin:)  without any errors thrown.

<details>
<summary>Full stacktrace</summary>

```
      at attachShadow (../../node_modules/react-shadow/src/index.js:23:39)
      at create (../../node_modules/react-dom/cjs/react-dom.development.js:17283:26)
      at commitHookEffectList (../../node_modules/react-dom/cjs/react-dom.development.js:17307:3)
      at HTMLUnknownElement.apply (../../node_modules/react-dom/cjs/react-dom.development.js:149:14)
      at Object.dispatchEvent (../../node_modules/react-dom/cjs/react-dom.development.js:199:16)
      at apply (../../node_modules/react-dom/cjs/react-dom.development.js:256:31)
      at invokeGuardedCallback (../../node_modules/react-dom/cjs/react-dom.development.js:18774:9)
      at apply (../../node_modules/scheduler/cjs/scheduler-tracing.development.js:207:34)
      at passiveEffectCallback (../../node_modules/react-dom/cjs/react-dom.development.js:18822:5)
      at flushPassiveEffects (../../node_modules/react-dom/cjs/react-dom.development.js:20570:3)
      at scheduleRootUpdate (../../node_modules/react-dom/cjs/react-dom.development.js:20600:10)
      at updateContainerAtExpirationTime (../../node_modules/react-dom/cjs/react-dom.development.js:20657:10)
      at ReactRoot.updateContainer [as render] (../../node_modules/react-dom/cjs/react-dom.development.js:20953:3)
      at render (../../node_modules/react-dom/cjs/react-dom.development.js:21105:12)
      at Object.legacyRenderSubtreeIntoContainer [as render] (../../node_modules/react-dom/cjs/react-dom.development.js:21155:12)
      at render (../../node_modules/react-dom/cjs/react-dom-test-utils.development.js:1175:14)
      at render (../../node_modules/@testing-library/react/dist/index.js:82:3)
      at SampleComponent (src/index.test.js:10)
```

</details>

**Comment by alexkrolick** [comment]
My first thought is that JSDOM may not support shadow dom

**Comment by ReasonableDeveloper** [comment]
Shadow DOM seems to be supported https://github.com/jsdom/jsdom/blob/75a921eab52c239b2468e08be9f547f46c7f86bd/lib/jsdom/living/helpers/shadow-dom.js.
The only open issue about shadow DOM support in JSDOM I could find was a missing descriptor. https://github.com/jsdom/jsdom/issues/2602

Should I rather open an issue inside the JSDOM repository?

**Comment by alexkrolick** [comment]
Are you on JSDOM 12.2.0 or higher?

https://github.com/jsdom/jsdom/blob/master/Changelog.md

The Jest default is 11 for Node 6 suppport

**Comment by andreupifarre** [comment]
When creating a `closed` ShadowDom I use `this._shadowRoot = this.attachShadow({mode: 'closed'});` when I refer to this property later in the code I notice `this._shadowRoot` is undefined.
Investigating a bit more I realised, properties seem to be all undefined.

for instance `button.print()` always prints undefined:

`class TestOne extends HTMLElement {
  constructor() {
    super()
    this.v = 14444
  }

  print() {
    console.log(2222, this.v)
  }
}

window.customElements.define('test-one', TestOne);
const test1 = document.createElement('test-one');
console.log(test1.print())`

**Comment by ReasonableDeveloper** [comment]
> You can use a newer version by adding a package like this one theneva/jest-environment-jsdom-thirteen

Create-react-app seems to use the msot recent version of jsdom. https://github.com/facebook/create-react-app/blob/404af90d9a4d3e2cc38ccb905ad8275480f5aeb7/packages/react-scripts/package.json#L59

Should I report this bug in jsdom instead?

**Comment by kentcdodds** [comment]
That's version 14, not 15
