### ISSUE TITLE
TypeError: Cannot read property 'current' of undefined

### ISSUE THREAD

**Issue by charlesdobson** [testing-library/react-testing-library#520]
### Current Package Versions
- `react`: 16.10.2
- `react-dom`: 16.10.2
- `jest`: 24.9.0
- `node`: 10.16.3

### Added Package Versions
- `@testing-library/dom`: ^6.10.0
- `@testing-library/jest-dom`: ^4.2.3
- `@testing-library/react`: ^9.3.1
- `@testing-library/user-event`: ^7.1.2

### Relevant code or config:

```js
import React from 'react';
import { render } from '@testing-library/react';
import '@testing-library/jest-dom/extend-expect';

test('react-testing-library hello world', () => {
    const {getByText} = render(
        <div>Hello</div>
    );
    expect(getByText('Hello')).toBeInTheDocument();
});
```

### What you did:

I'm trying to add react-testing-library to a new project at work. After adding the packages, I added a simple test (used in a different project) to verify the library is now ready to use.

### What happened:

After trying to run the simple test above, the test fails and outputs this:

```js
  ✕ react-testing-library hello world (6ms)

  ● react-testing-library hello world

    TypeError: Cannot read property 'current' of undefined

      4 | 
      5 | test('react-testing-library hello world', () => {
    > 6 |     const {getByText} = render(
        |                         ^
      7 |         <div>Hello</div>
      8 |     );
      9 |     expect(getByText('Hello')).toBeInTheDocument();

      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1100:57)
      at render (node_modules/@testing-library/react/dist/pure.js:82:26)
      at Object.<anonymous>.test (src/tmp.test.js:6:25)

```

### Suggested solution:

Similar Issue: https://github.com/testing-library/react-testing-library/issues/439
I'm assuming there is a package mismatch somewhere, as others have experienced similar difficulties. I've tried multiple combinations and haven't had any luck getting it to run. Any help is appreciated!

**Comment by charlesdobson** [comment]
Looks like the problem was in my **jest.setup.js** document. I was mocking react-dom with

`jest.mock('react-dom');`

Removing this makes the test run as expected

![Screen Shot 2019-11-07 at 3 15 48 PM](https://user-images.githubusercontent.com/36612750/68424270-9e7ac680-0171-11ea-8f2e-8f2c66924d81.png)

I ended up upgrading to these versions:

- `react`: 16.11.0
- `react-dom`: 16.11.0
- `react-test-renderer`: ^16.11.0
- `jest`: 24.9.0
- `node`: 10.16.3
- `@testing-library/dom`: ^6.10.1
- `@testing-library/jest-dom`: ^4.2.3
- `@testing-library/react`: ^9.3.2
- `@testing-library/user-event`: ^7.1.2

Closing this now. Hopefully this will help someone else if they are having a similar issue!
