### ISSUE TITLE
Error: Failed to load config "./node_modules/kcd-scripts/eslint.js" to extend from.

### ISSUE THREAD

**Issue by kpodmasko** [testing-library/react-testing-library#556]
Hi! Thanks for lib. Give me please some feedback about it. 

I have an error:
```
[!] (eslint plugin) Error: Failed to load config "./node_modules/kcd-scripts/eslint.js" to extend from.
Referenced from: /Users/konstantinpodmasko/VSCode/turbo-render/node_modules/@testing-library/dom/package.json
node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js
Error: Failed to load config "./node_modules/kcd-scripts/eslint.js" to extend from.
Referenced from: /Users/konstantinpodmasko/VSCode/turbo-render/node_modules/@testing-library/dom/package.json
    at configMissingError (/Users/konstantinpodmasko/VSCode/turbo-render/node_modules/eslint/lib/cli-engine/config-array-factory.js:264:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/konstantinpodmasko/VSCode/turbo-render/node_modules/eslint/lib/cli-engine/config-array-factory.js:824:23)
    at ConfigArrayFactory._loadExtends (/Users/konstantinpodmasko/VSCode/turbo-render/node_modules/eslint/lib/cli-engine/config-array-factory.js:729:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/konstantinpodmasko/VSCode/turbo-render/node_modules/eslint/lib/cli-engine/config-array-factory.js:658:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/konstantinpodmasko/VSCode/turbo-render/node_modules/eslint/lib/cli-engine/config-array-factory.js:594:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (/Users/konstantinpodmasko/VSCode/turbo-render/node_modules/eslint/lib/cli-engine/config-array-factory.js:338:25)
    at ConfigArrayFactory.loadInDirectory (/Users/konstantinpodmasko/VSCode/turbo-render/node_modules/eslint/lib/cli-engine/config-array-factory.js:431:16)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/konstantinpodmasko/VSCode/turbo-render/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:328:46)

1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

My project worked fine with react-testing-library for 2 month. This lib was used in .test.js/jsx files with preloaded queries:
```jsx
import { render, fireEvent } from '@testing-library/react';
...
const {getByTestId}  = render(<SomeComponent/>);
....
expect(getByTestId(...)).toBe(...)
```
but one time I created a custom query and imported helpers for it.

```jsx
import domTestingLib from '@testing-library/dom';

const {
  queryHelpers: { queryAllByAttribute, queryByAttribute, getElementError },
} = domTestingLib;
```

After that import I had an error listed above.

package.json

```json
{
  "name": "turbo-render",
  "license": "UNLICENSED",
  "version": "1.0.3",
  "main": "dist/index.js",
  "module": "dist/index.es.js",
  "jsnext:main": "dist/index.es.js",
  "engines": {
    "node": ">=10",
    "npm": ">=5"
  },
  "scripts": {
    "test": "jest --watch --config ./jest.config.js",
    "test:staged": "jest --config ./jest.config.js --bail --findRelatedTests",
    "build": "rollup -c",
    "start": "rollup -c -w",
    "lint": "eslint src -c \".eslintrc.json\" --ext js,jsx",
    "checkcommit": "lint-staged",
    "docs:server": "npx styleguidist server",
    "docs:build": "npx styleguidist build",
    "format:nojs": "prettier 'docs/**/**/**/*.md' 'src/**/**/**/*.md' 'src/**/**/**/*.scss' --write"
  },
  "peerDependencies": {
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-router-dom": "^5.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.7.4",
    "@babel/plugin-external-helpers": "^7.7.4",
    "@babel/plugin-transform-modules-commonjs": "^7.7.4",
    "@babel/preset-env": "^7.7.4",
    "@babel/preset-react": "^7.7.4",
    "@svgr/rollup": "^2.4.1",
    "autoprefixer": "^9.7.2",
    "babel-eslint": "^10.0.3",
    "babel-jest": "^24.9.0",
    "babel-loader": "^8.0.6",
    "cross-env": "^5.1.4",
    "css-loader": "^3.2.0",
    "eslint": "^6.1.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-prettier": "^4.3.0",
    "eslint-config-standard": "^11.0.0",
    "eslint-config-standard-react": "^6.0.0",
    "eslint-plugin-import": "^2.17.3",
    "eslint-plugin-jest": "^22.6.4",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-node": "^7.0.1",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-promise": "^4.0.0",
    "eslint-plugin-react": "^7.13.0",
    "eslint-plugin-standard": "^3.1.0",
    "history": "^4.10.1",
    "husky": ">=1",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^24.9.0",
    "lerna": "^3.19.0",
    "lint-staged": ">=8",
    "node-sass": "^4.13.0",
    "prettier": "^1.19.1",
    "react-scripts": "3.2.0",
    "react-styleguidist": "^10.2.1",
    "react-test-renderer": "^16.12.0",
    "rollup": "^0.64.1",
    "rollup-plugin-babel": "^4.3.3",
    "rollup-plugin-commonjs": "^9.1.3",
    "rollup-plugin-eslint": "^7.0.0",
    "rollup-plugin-node-builtins": "^2.1.2",
    "rollup-plugin-node-resolve": "^3.3.0",
    "rollup-plugin-peer-deps-external": "^2.2.0",
    "rollup-plugin-postcss": "^1.6.2",
    "rollup-plugin-url": "^1.4.0",
    "sass-loader": "^8.0.0",
    "style-loader": "^1.0.0",
    "stylelint": "^12.0.0",
    "stylelint-config-recommended-scss": "^4.1.0",
    "stylelint-scss": "^3.13.0",
    "url-loader": "^3.0.0"
  },
  "files": [
    "dist"
  ],
  "husky": {
    "hooks": {
      "pre-commit": "lerna run --concurrency 1 --stream checkcommit"
    }
  },
  "lint-staged": {
    "*.{js,jsx}": [
      "eslint src -c \".eslintrc.json\" --ext js,jsx --fix",
      "git add",
      "yarn test:staged"
    ],
    "*.scss": [
      "stylelint --syntax=scss --fix",
      "git add"
    ],
    "*.{scss, md}": [
      "yarn format:nojs",
      "git add"
    ]
  },
  "stylelint": {
    "extends": "stylelint-config-recommended-scss",
    "rules": {
      "selector-pseudo-class-no-unknown": [
        true,
        {
          "ignorePseudoClasses": [
            "global",
            "local"
          ]
        }
      ],
      "no-descending-specificity": null
    }
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.25",
    "@fortawesome/free-solid-svg-icons": "^5.11.2",
    "@fortawesome/react-fontawesome": "^0.1.8",
    "@testing-library/dom": "^6.11.0",
    "@testing-library/react": "^9.4.0",
    "kcd-scripts": "^1.13.0",
    "prop-types": "^15.7.2",
    "react-popup": "^0.10.0"
  }
}

```
I have eslint files:
eslintrc(1)
eslintignore(2)
 /src/eslintrc(3)
 /example/eslintrc(4)
 /example/eslintignore(5)

eslintrc(1):
```json
{
  "root": true,
  "extends": [
    "airbnb",
    "prettier",
    "prettier/react",
    "plugin:jest/recommended"
  ],
  "plugins": ["react", "prettier", "jest"],
  "rules": {
    "react/jsx-filename-extension": [
      1,
      {
        "extensions": [".js", "jsx"]
      }
    ],
    "prettier/prettier": "error",
    "max-len": ["error", 100],
    "import/no-unresolved": 0,
    "react/prop-types": [
      1,
      {
        "skipUndeclared": true
      }
    ]
  },
  "parser": "babel-eslint",
  "globals": {
    "document": "readonly"
  }
}

```
eslintignore(2):
```
node_modules/*
dist/*
example/*
src/**/*.css
src/**/*.scss
src/images/*
```
/src/eslintrc(3)
```json
{
  "env": {
    "jest": true
  }
}
```
/example/eslintrc(4)
```json
{
  "extends": ["../.eslintrc"]
}
```
/example/eslintignore(5)
```
src/serviceWorker.js
node_modules/*
public/*
build/*
node_modules
```

**Comment by kpodmasko** [comment]
the error is caused by bug in rollup-plugin-eslint, described here https://github.com/TrySound/rollup-plugin-eslint/issues/40.

downgrade from 7 to 6 version fixed error
