### ISSUE TITLE
render method just crashes when called with <iframe />

### ISSUE THREAD

**Issue by DanielHara** [testing-library/react-testing-library#568]
- `react-testing-library` version: 9.3.0
- `react` version: 16.11.0
- `node` version: 12.13.0
- `yarn` version: 1.19.1
- `jest` version: 24.9.0
- `jsdom` version: 11.12.0

### Relevant code or config:

```js
import { render } from '@testing-library/react'

it('should render iframe without crashing', () => {
    const container = render(<iframe />)
})
```

### What you did:
Just ran the test above.

### What happened:
```
TypeError: Cannot read property 'length' of undefined

      at windowCleaner (../../node_modules/jsdom/lib/jsdom/browser/Window.js:487:41)
      at windowCleaner (../../node_modules/jsdom/lib/jsdom/browser/Window.js:488:9)
      at Window.close (../../node_modules/jsdom/lib/jsdom/browser/Window.js:495:6)


 console.error ../../node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Uncaught [TypeError: Cannot read property 'querySelectorAll' of null]
        at reportException (/home/hara/github/epages-ui/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at Timeout.callback [as _onTimeout] (/home/hara/github/epages-ui/node_modules/jsdom/lib/jsdom/browser/Window.js:680:7)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) TypeError: Cannot read property 'querySelectorAll' of null
        at Object.highlightAllUnder (/home/hara/github/epages-ui/node_modules/unexpected-dom/node_modules/prismjs/prism.js:188:44)
        at highlightAll (/home/hara/github/epages-ui/node_modules/unexpected-dom/node_modules/prismjs/prism.js:177:5)
        at Timeout.callback [as _onTimeout] (/home/hara/github/epages-ui/node_modules/jsdom/lib/jsdom/browser/Window.js:678:19)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7)

console.error ../../node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Uncaught [TypeError: Cannot read property 'querySelectorAll' of null]
        at reportException (/home/hara/github/epages-ui/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at Timeout.callback [as _onTimeout] (/home/hara/github/epages-ui/node_modules/jsdom/lib/jsdom/browser/Window.js:680:7)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) TypeError: Cannot read property 'querySelectorAll' of null
        at Object.highlightAllUnder (/home/hara/github/epages-ui/node_modules/prismjs/prism.js:174:44)
        at highlightAll (/home/hara/github/epages-ui/node_modules/prismjs/prism.js:163:5)
        at Timeout.callback [as _onTimeout] (/home/hara/github/epages-ui/node_modules/jsdom/lib/jsdom/browser/Window.js:678:19)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7)



```

### Reproduction:
Just try to call the `render` method from  `react-testing-library` with an `<iframe />`

### Problem description:
Impossible to test any component which contains an `<iframe />`.

**Comment by ahmdtalaat** [comment]
I tried to reproduce the error but the test ran just fine with no errors.

Tested Code
```javascript
import React from "react";
import { render } from "@testing-library/react";

it("should render iframe", () => {
  const c = render(<iframe />);
});
```

**Comment by DanielHara** [comment]
> I tried to reproduce the error but the test ran just fine with no errors.
> 
> Tested Code
> 
> ```js
> import React from "react";
> import { render } from "@testing-library/react";
> 
> it("should render iframe", () => {
>   const c = render(<iframe />);
> });
> ```

@ahmdtalaat , could you post here what versions of `react` and `@testing-library/react` you are using?

**Comment by DanielHara** [comment]
I'm closing this, the problem has to do with an jsdom issue: https://github.com/jsdom/jsdom/pull/1694
