### ISSUE TITLE
ReferenceError: Cannot access 'observer' before initialization

### ISSUE THREAD

**Issue by dominikzogg** [testing-library/react-testing-library#621]
- `@testing-library/react` version:
- `react` version: 16.13.1
- `node` version: 13.11.0
- `npm` (or `yarn`) version: 6.13.7

### Relevant code or config:

https://github.com/chubbyphp/petstore-react/blob/master/src/__tests__/Component/Form/PetForm.test.tsx

### What you did:

```
npm test -- --watchAll
```

### What happened:

```
petstore-react/node_modules/@testing-library/dom/dist/wait-for.js:41
      (0, _helpers.setImmediate)(() => observer.disconnect());
                                                ^

ReferenceError: Cannot access 'observer' before initialization
    at Immediate.<anonymous> (/home/schreiner/Documents/webpages/petstore-react/node_modules/@testing-library/dom/dist/wait-for.js:41:49)
    at processImmediate (internal/timers.js:456:21)
/home/schreiner/Documents/webpages/petstore-react/node_modules/@testing-library/dom/dist/wait-for.js:41
      (0, _helpers.setImmediate)(() => observer.disconnect());                                                ^ReferenceError: Cannot access 'observer' before initialization    at Immediate.<anonymous> (/home/schreiner/Documents/webpages/petstore-react/node_modules/@testing-library/dom/dist/wait-for.js:41:49)    at processImmediate (internal/timers.js:456:21)
```

```
TypeError: MutationObserver is not a constructor

      214 |     fireEvent.click(getByTestId('submit-pet'));
      215 | 
    > 216 |     await waitForElement(() =>
          |           ^
      217 |         getByTestId('submit-pet')
      218 |     );
```

### Reproduction:

Run tests on: https://github.com/chubbyphp/petstore-react

### Problem description:

This problem apears when upgrading to 10.*, worked well on 9.*

**Comment by pushred** [comment]
@dominikzogg looks like https://github.com/testing-library/dom-testing-library/issues/477 is discussing this issue with different resolution options

**Comment by dominikzogg** [comment]
@pushred thanks, adding `jest-environment-jsdom-sixteen` solved the issue
