### ISSUE TITLE
 Error: Uncaught [TypeError: data.element._node.getTotalLength is not a function]

### ISSUE THREAD

**Issue by suresh777** [testing-library/react-testing-library#652]
I am using Chartist library to draw donut. I am writing test case for donut component. If i render component it is working fine, But if i try to await for anything i am getting this error.

```
Chartist code:
var chart = new Chartist.Pie('.ct-chart', {
  series: [10, 20, 50, 20, 5, 50, 15],
  labels: [1, 2, 3, 4, 5, 6, 7]
}, {
  donut: true,
  showLabel: false
});

chart.on('draw', function(data) {
  if(data.type === 'slice') {
    // Get the total path length in order to use for dash array animation
    **var pathLength = data.element._node.getTotalLength();**

    // Set a dasharray that matches the path length as prerequisite to animate dashoffset
    data.element.attr({
      'stroke-dasharray': pathLength + 'px ' + pathLength + 'px'
    });

TestComponent:
   await waitForElement(() => {

   })
 Error: Uncaught [TypeError: data.element._node.getTotalLength is not a function]
        at reportException (/Users/ram/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at Timeout.callback [as _onTimeout] ((/Users/ram/node_modules/jsdom/lib/jsdom/browser/Window.js:680:7)
        at listOnTimeout (internal/timers.js:537:17)

```

**Comment by eps1lon** [comment]
Unfortunately this is not something we control. You probably run your tests in jsdom (via jest?) in which `getTotalLength` is not supported: https://github.com/jsdom/jsdom/issues/1330.
