### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by r3mtm** [testing-library/react-testing-library#771]
- `@testing-library/react` version: "^10.4.9"
- Testing Framework and version: "react ^16.13.1"
  
- DOM Environment: "jest-environment-jsdom-sixteen": "^1.0.3"
  

### Relevant code or config:

```js
describe('Fetching the given todo with `id` in the url', () => {

    const sampleResponse = {
        todoId: 'ce28159b-e2cf-43d8-892c-ac15af89cf43',
        todoTitle: 'Sample title',
        username: 'foo',
        lastUpdated: '1597731817123',
        todoItems: [
            {
                todoIndex: 0,
                todoItem: 'Item 1',
                strike: false
            },
            {
                todoIndex: 1,
                todoItem: 'Item 2',
                strike: false
            },
            {
                todoIndex: 2,
                todoItem: 'Item 3',
                strike: false
            },
        ]
    }

    const server = setupServer(
        rest.get('*', (req, res, ctx) => {
            return res(
                ctx.status(200),
                ctx.set({ 'Access-Control-Allow-Origin': '*' }),
                ctx.body(sampleResponse)
            )
        })
    )

    it('should render the ', async () => {
        server.listen();
        setupWithHistoryProps();
        const todos = await screen.findAllByText(/Item/);
        expect(todos.length).toBe(sampleResponse.todoItems.length);
    })
});
```

### What you did:
When i tried to run the test i got the following error

"Error: Error: connect ECONNREFUSED 127.0.0.1:8080"

### What happened:

Error: connect ECONNREFUSED 127.0.0.1:8080
        at Object.dispatchError (/home/remil/study/react/react/project/notes-project/node_modules/jest-environment-jsdom-sixteen/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:62:19)
        at EventEmitter.<anonymous> (/home/remil/study/react/react/project/notes-project/node_modules/jest-environment-jsdom-sixteen/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:654:18)
        at EventEmitter.emit (events.js:327:22)
        at Request.<anonymous> (/home/remil/study/react/react/project/notes-project/node_modules/jest-environment-jsdom-sixteen/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:390:47)
        at Request.emit (events.js:315:20)
        at Request.onRequestError (/home/remil/study/react/react/project/notes-project/node_modules/request/request.js:877:8)
        at ClientRequest.emit (events.js:315:20)
        at Socket.socketErrorListener (_http_client.js:432:9)
        at Socket.emit (events.js:315:20)
        at emitErrorNT (internal/streams/destroy.js:84:8) undefined

  console.error node_modules/jest-environment-jsdom-sixteen/node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Not implemented: window.alert
        at module.exports (/home/remil/study/react/react/project/notes-project/node_modules/jest-environment-jsdom-sixteen/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
        at alert (/home/remil/study/react/react/project/notes-project/node_modules/jest-environment-jsdom-sixteen/node_modules/jsdom/lib/jsdom/browser/Window.js:728:7)
        at /home/remil/study/react/react/project/notes-project/src/container/Todo/Editor/TodoEditor.js:86:13
        at processTicksAndRejections (internal/process/task_queues.js:97:5) undefined

### Suggested solution:

If I move the declaration of server inside the "it" block, everything works perfectly.

```js
describe('Fetching the given todo with `id` in the url', () => {

    const sampleResponse = {
        todoId: 'ce28159b-e2cf-43d8-892c-ac15af89cf43',
        todoTitle: 'Sample title',
        username: 'foo',
        lastUpdated: '1597731817123',
        todoItems: [
            {
                todoIndex: 0,
                todoItem: 'Item 1',
                strike: false
            },
            {
                todoIndex: 1,
                todoItem: 'Item 2',
                strike: false
            },
            {
                todoIndex: 2,
                todoItem: 'Item 3',
                strike: false
            },
        ]
    }

    it('should render the ', async () => {
        const server = setupServer(
          rest.get('*', (req, res, ctx) => {
             return res(
                 ctx.status(200),
                 ctx.set({ 'Access-Control-Allow-Origin': '*' }),
                 ctx.body(sampleResponse)
              )
          })
       )
        server.listen();
        setupWithHistoryProps();
        const todos = await screen.findAllByText(/Item/);
        expect(todos.length).toBe(sampleResponse.todoItems.length);
    })
});
```

Is something wrong with my code?

**Comment by eps1lon** [comment]
Looks like an issue with your mocked server. Try asking on StakckOverflow or the [testing library discord](https://discord.com/channels/723559267868737556/723565500986032201).
