### ISSUE TITLE
Issue with react-dom 17

### ISSUE THREAD

**Issue by vertic4l** [testing-library/react-testing-library#968]
- `@testing-library/react` version: 12.1.0
- Testing Framework and version:

- DOM Environment:

### What you did:

updated to react 17 and react-dom 17

### What happened:

```
TypeError: Cannot read property 'createEvent' of null
    at Object.invokeGuardedCallbackDev (/src/node_modules/react-dom/cjs/react-dom.development.js:3905:26)
    at invokeGuardedCallback (/src/node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at flushPassiveEffectsImpl (/src/node_modules/react-dom/cjs/react-dom.development.js:23543:11)
    at unstable_runWithPriority (/src/node_modules/scheduler/cjs/scheduler.development.js:468:12)
    at runWithPriority$1 (/src/node_modules/react-dom/cjs/react-dom.development.js:11276:10)
    at flushPassiveEffects (/src/node_modules/react-dom/cjs/react-dom.development.js:23447:14)
    at Object.<anonymous>.flushWork (/src/node_modules/react-dom/cjs/react-dom-test-utils.development.js:992:10)
    at Immediate.<anonymous> (/src/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1003:11)
```

### Reproduction:

Update to react 17 and react-dom 17, and use fireEvent or userEvent in test.

### Problem description:

See "what happend" from above

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by vertic4l** [comment]
this issue comes from async jest test when using waitFor:

```
it("xxxx", async () => {
  waitFor()
})
```

the correct way is:

```
it("xxxx", async () => {
  await waitFor()
})
```
