### ISSUE TITLE
waitFor throwing an error when a rejected promise is used in a mock

### ISSUE THREAD

**Issue by lourd** [testing-library/react-testing-library#982]
- `@testing-library/react` version: 12.1.2
- Testing Framework and version: Jest 26.6.0
- DOM Environment: jsdom 16.4.0
- Node 16.10.0

### What you did:

I have a test where I mock the value of a function to return a `Promise.reject`. Then I use the `waitFor` helper to wait for the assertion to be true since some state ends up being changed in a `useEffect`.

```js
import { useEffect, useState, createContext, useContext } from "react";
import { act, render, screen, waitFor } from "@testing-library/react";

const Authenticate = {
  get: () => Promise.resolve({ accessToken: 'foo'})
}

const delay = (ms) => new Promise(res => setTimeout(res, ms))

const initialAuthState = {
  accessToken: null,
  error: null,
};

const AuthContext = createContext(initialAuthState);

const AuthProvider = ({ children }) => {
  const [authState, setAuthState] = useState(initialAuthState);
  useEffect(() => {
    Authenticate.get()
      .then(setAuthState)
      // Even though this has a catch handler, the rejected promise still somehow causes
      // an exception to be thrown in the test
      .catch((error) => {
        console.log('Catching authenticate error:', error)
        setAuthState((prev) => ({ ...prev, error }))
      });
  }, []);

  return (
    <AuthContext.Provider value={authState}>{children}</AuthContext.Provider>
  );
};

const accessToken = "secretToken";
const errorMsg = "why the heck is this being thrown";

const authStateWithToken = {
  accessToken,
  error: null,
};

const TestComp = () => {
  return (
    <AuthProvider>
      <ChildComp />
    </AuthProvider>
  );
};

const ChildComp = () => {
  const { accessToken, error } = useContext(AuthContext);
  return (
    <div>
      <h1 data-testid="accessToken">{accessToken}</h1>
      <h1 data-testid="error">{error}</h1>
    </div>
  );
};

it("Sets authState based on the response of authenticate", async () => {
  const spy =  jest.spyOn(Authenticate, 'get')
  spy.mockReturnValue(
    Promise.resolve(authStateWithToken)
  );

  await act(async () => {
    render(<TestComp />);
    // Even though this test is doing the same thing, it doesn't throw an exception
    await waitFor(() => {
      expect(screen.getByTestId("accessToken")).toHaveTextContent(accessToken);
    });
  });
  expect(screen.getByTestId("error")).toHaveTextContent("");
  spy.mockRestore()
});

it("Catches error and sets error in authState", async () => {
  const spy = jest.spyOn(Authenticate, 'get')
  // For some reason this mock Promise reject is being thrown from the waitFor helper
  spy.mockReturnValue(Promise.reject(errorMsg));

  // If I use `mockRejectedValue`, there's no exception thrown 😕
  // spy.mockRejectedValue(errorMsg);

  // If I add a little delay, there's no exception thrown 😕😕
  // spy.mockReturnValue(delay(100).then(() => Promise.reject(errorMsg)));

  await act(async () => {
    render(<TestComp />);
    console.log('acting...')
    await waitFor(() => {
      console.log('Waiting for... what is it?', screen.getByTestId("error").textContent)
    //   // If you uncomment the try-catch, there's no error
    //   // try {
    //   // ❌❌❌ For some reason this throws the rejected promise 😕
      expect(screen.getByTestId("error")).toHaveTextContent(errorMsg);
      console.log('after expect')
    //   // } catch {}
    });
  });
  expect(screen.getByTestId("accessToken")).toHaveTextContent("");
  expect(screen.getByTestId("error")).toHaveTextContent(errorMsg);
  spy.mockRestore()
});
```

### What happened:

<details>
<summary>Console output</summary>

```sh
(node:64708) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(Use `node --trace-warnings ...` to show where the warning was created)
 FAIL  src/AuthContext.test.js
  ✓ Sets authState based on the response of authenticateOrRedirect (28 ms)
  ✕ Catches error and sets error in authState (9 ms)

  ● Catches error and sets error in authState

    thrown: "why the heck is this being thrown"

      at _getError (node_modules/jest-circus/build/utils.js:442:18)
          at Array.map (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        1.696 s, estimated 2 s
Ran all test suites related to changed files.
```

</details>

### Reproduction:

See a full reproduction here https://github.com/lourd/testing-library-wait-error-repro/blob/main/src/AuthContext.test.js

### Problem description:

`waitFor` is supposed to catch errors thrown inside of it. It seems to do this in most cases, but not in this case where a rejected promise is involved.

If I omit the `waitFor` from the `act` block entirely and do my assertion after it, there's no problem, as long as I keep the callback given to `act` an `async` function (even though nothing is `await`ed). If I omit the `async`, the test passes, but I get errors in my console about updating state outside of an `act` block.

<details>
<summary>Details</summary>

```sh
 PASS  src/AuthContext.test.js
  ✓ Sets authState based on the response of authenticateOrRedirect (28 ms)
  ✓ Catches error and sets error in authState (49 ms)

  console.error
    Warning: Do not await the result of calling act(...) with sync logic, it is not a Promise.

      at printWarning (node_modules/react-dom/cjs/react-dom-test-utils.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom-test-utils.development.js:43:5)
      at Object.then (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1120:11)

  console.error
    Warning: An update to AuthProvider inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at AuthProvider (/Users/louis/code/testing-library-error-repro/src/AuthContext.js:15:32)
        at TestComp

      18 |     authenticateOrRedirect()
      19 |       .then(setAuthState)
    > 20 |       .catch((error) => setAuthState((prev) => ({ ...prev, error })));
         |                         ^
      21 |   }, []);
      22 |
      23 |   return (

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (node_modules/react-dom/cjs/react-dom.development.js:24064:9)
      at setAuthState (node_modules/react-dom/cjs/react-dom.development.js:16135:9)
      at src/AuthContext.js:20:25
```

</details>

### Suggested solution:

Fix `waitFor`?

**Comment by JohnKearney2020** [comment]
I had a similar issue.

I was trying:

`clientServicePatchClientSpy.mockReturnValue(Promise.reject(new Error('testValueError')));`

For whatever reason, that made my test error out. Not sure why - I've done it that way in other tests with no issues. I stumbled across [.mockRejectValue()](https://jestjs.io/docs/mock-function-api#mockfnmockrejectedvaluevalue), tried that, and for whatever reason that made the mock and the test work properly:

`clientServicePatchClientSpy.mockRejectedValue(new Error('Our test error'));`

I'm new to front end testing, so it may be a simple issue I am overlooking, but thought I'd share for any other folks that stumble on this later.

**Comment by eps1lon** [comment]
Without knowing where this rejected promise is used, we can't know whether we should be able to catch it.

Promise are not caught by default in node. You have to explicitly `await` them and only if you do this in throughout the callstack is JS able to catch it.

But `waitFor` is running concurrently. It's job isn't to catch promises in other tasks. It just waits for the condition to be true. Your frontend code should deal with the rejected promise.

**Comment by lourd** [comment]
I've updated the PR description with a narrower reproduction to illustrate the issue more clearly.

The bug here is that I _am_ catching/handling my rejected promise appropriately, but somehow it's still causing an exception to be thrown. There's some kind of strange behavior with what will cause the `waitFor` block to throw an exception. I've tried to illustrate the strangeness with 3 different setups. These are in the PR description, too, with parts of each setup commented out.

1. Using `mockReturnValue` with Promise.reject. This throws an exception

```tsx
  const spy = jest.spyOn(Authenticate, 'get')
  // For some reason this mock Promise reject is being thrown from the waitFor helper
  spy.mockReturnValue(Promise.reject(errorMsg));

  await act(async () => {
    render(<TestComp />);
    await waitFor(() => {
      // This logs the errorMsg, as expected
      console.log('Waiting for... what is it?', screen.getByTestId("error").textContent)
      // ❌❌❌ But for some reason this ends up throwing an exception
      expect(screen.getByTestId("error")).toHaveTextContent(errorMsg);
    });
  });
  expect(screen.getByTestId("accessToken")).toHaveTextContent("");
  expect(screen.getByTestId("error")).toHaveTextContent(errorMsg);
```

2. Using `mockRejectedValue`. This does **not** throw an exception

```tsx
  const spy = jest.spyOn(Authenticate, 'get')
  // Using mockRejectedValue, there's no exception thrown
  spy.mockRejectedValue(errorMsg);

  await act(async () => {
    render(<TestComp />);
    await waitFor(() => {
      expect(screen.getByTestId("error")).toHaveTextContent(errorMsg);
    });
  });
  expect(screen.getByTestId("accessToken")).toHaveTextContent("");
  expect(screen.getByTestId("error")).toHaveTextContent(errorMsg);
```

3. Adding a delay. This also does **not** throw an exception

```tsx
  const delay = (ms) => new Promise(res => setTimeout(res, ms))
  const spy = jest.spyOn(Authenticate, 'get')
  // If I add a little delay, there's no exception thrown 😕😕
  spy.mockReturnValue(delay(100).then(() => Promise.reject(errorMsg)));

  await act(async () => {
    render(<TestComp />);
    await waitFor(() => {
      expect(screen.getByTestId("error")).toHaveTextContent(errorMsg);
    });
  });
  expect(screen.getByTestId("accessToken")).toHaveTextContent("");
  expect(screen.getByTestId("error")).toHaveTextContent(errorMsg);
```

I just realized if I move the `waitFor` outside of the `act` block, and remove the `async` modifier on the `act` callback and don't `await` the return value, then there's also no issue. Perhaps this is a misunderstanding of how to use `waitFor`, that it should not be called in `act`.

**Comment by RLiriaVA** [comment]
Hi sr do you have wsp?

**Comment by eps1lon** [comment]
I have no idea why this is happening. I hope that this is some oddity with Jest. You can fix it by either moving `render` outside of `act` (which you should do anyway since render is already wrapped in act. 

Or, as you already identified, using `spy.mockRejectedValue` instead of `spy.mockReturnValue(Promise.reject(errorMsg))`.

Note that Jest says that `mockRejectedValue` is sugar for `spy.mockImplementation(() => Promise.reject(errorMsg));` not `spy.mockReturnValue`. I think Jest just gets confused when you create a rejected promise during test evaluation instead of creating a rejected promise when an implementation is called.

**Comment by iulianalbu** [comment]
@eps1lon Thanks, I've placed the `render` outside of `act` and it's working.
